### ISSUE TITLE
BYE-016/1대1 채팅

### ISSUE THREAD

**Issue by jungo0** [codestates-seb/seb44_main_022#20]
## 요구사항 ID

BYE-016

## 요구사항

가게 디테일 페이지에서 1대1 채팅을 할 수 있다.

## 상세 요구사항

- 가게 디테일 페이지에서 1대1 채팅을 할 수 있다.
- 구매자는 판매자에게 1대1로 채팅 문의를 할 수 있다.
- 각각의 가게에서 했던 채팅은 가게 디테일 페이지의 채팅창에서만 확인이 가능하다.

## TODO
- [x] 가게 디테일 페이지에서 1대1 채팅을 할 수 있다.
- [x] 구매자는 판매자에게 1대1로 채팅 문의를 할 수 있다.
- [x] 각각의 가게에서 했던 채팅은 가게 디테일 페이지의 채팅창에서만 확인이 가능하다.
