### ISSUE TITLE
BYE-020/장바구니

### ISSUE THREAD

**Issue by KimJunpyo** [codestates-seb/seb44_main_022#24]
## 요구사항 ID

BYE-020

## 요구사항

장바구니

## 상세 요구사항

- 구매를 원하는 제품들을 장바구니에 등록
- 등록된 제품들의 가격 총합을 표시
- 등록된 제품들을 모두 제거 or 선택된 제품들 제거 가능
- 선택된 제품들만 주문 가능

## TODO
- [x] 제품을 장바구니에 등록
- [x] 등록된 제품 목록 표시
- [x] 제품별 간략 정보 표시
- [x] 제품 목록 가격 총합 표시
- [x] 제품 선택
- [x] 선택된 제품 삭제
- [x] 선택된 제품만 주문

## 개발 시간
1일

**Comment by KimJunpyo** [comment]
레이아웃 완

**Comment by KimJunpyo** [comment]
제품 리스트 표시, 선택, 기타 프론트단에서 할 수 있는 로직 처리 완
