### ISSUE TITLE
BYE-027/제품 상세 모달

### ISSUE THREAD

**Issue by jungo0** [codestates-seb/seb44_main_022#31]
## 요구사항 ID

BYE-027

## 요구사항

제품 상세 모달

## 상세 요구사항

- 가게 상세 페이지에서 제품을 클릭하면 모달창으로 제품의 상세정보가 표시된다.
- 버튼을 클릭시 장바구니에 담기고 다시 가게 상세페이지로 이동한다.

## TODO
- [x] 제품을 클릭하면 모달창으로 제품의 상세정보가 표시돼야 한다.
- [ ] 하단의 장바구니를 클릭 시 장바구니에 담긴다.
- [ ] 다시 가게 상세페이지로 돌아온다.

## 개발 시간
2일

**Comment by KimJunpyo** [comment]
레이아웃 완
