### ISSUE TITLE
BYE-025/가게 상세 페이지

### ISSUE THREAD

**Issue by KimJunpyo** [codestates-seb/seb44_main_022#34]
## 요구사항 ID

BYE-025

## 요구사항

가게 상세 페이지

## 상세 요구사항

- 가게의 상세 정보, 추천 커스텀 제품 리스트, 판매 제품 리스트 구현
- 상세 정보는 매장 이미지, 매장 이름, 커스텀되어 판매된 추천 제품들, 커스텀 가능한 제품들 표시
- 제품들을 클릭했을 때, 추천 커스텀 제품이면 상세 모달창 / 커스텀 가능한 제품이면 커스텀 모달창 출력

## TODO
- [ ] 가게의 상세 정보 표시
- [ ] 판매되었던 추천 커스텀 제품들 표시
- [ ] 클릭한 제품의 형태에 따라 다른 모달창 출력

## 개발 시간
3일
