### ISSUE TITLE
BYE-002/일반 자체 회원가입

### ISSUE THREAD

**Issue by oshyun00** [codestates-seb/seb44_main_022#40]
## 요구사항 ID

BYE-002

## 요구사항

일반 자체 회원 가입

## 상세 요구사항

- ID,  비밀번호, 닉네임을 전달받아 가입을 진행한다.

## TODO
- [ ] 각 항목당 유효성 검사 수행
- [ ] 유효성 조건이 맞지 않을시 에러 메세지 표시
- [ ] 유효성 조건이 맞으면 회원 DB에 저장

## 예상 개발 소요 기간
1일
