### ISSUE TITLE
BYE-012/커스텀 모달

### ISSUE THREAD

**Issue by jungo0** [codestates-seb/seb44_main_022#7]
## 요구사항 ID

BYE-012

## 요구사항

커스텀 모달

## 상세 요구사항

- 가게 상세 페이지에서 제품을 클릭하면 모달창으로 제품의 커스텀 화면이 표시된다.
- 고객이 직접 제품을 밑바탕으로 그림 또는 재료들을 활용해 커스텀한다. 
## TODO
- [x] 색상 선택, 레터링, 재료, 장식품 배치 기능
- [x] 각 기능, 재료, 장식품별 가격측정
- [x] 제품의 밑바탕은 on/off 처리
- [x] 커스텀이 완료된 제품은 이미지로 추출되어 시안으로 전송한다.

## 개발 시간
커스텀 총 개발 시간 1주일

**Comment by jungo0** [comment]
레이아웃 완료
