### ISSUE TITLE
BYE-008/마이페이지

### ISSUE THREAD

**Issue by Raros17** [codestates-seb/seb44_main_022#8]
## 요구사항 ID
BYE-008

## 요구사항
유저 프로필, 주문 내역, 찜 목록(보류.) 확인

## 상세 요구사항
- 마이페이지 진입시 유저 프로필, 주문 내역이 보이도록 한다.
- 찜 목록은 최하순위로 보류한다.

## TODO
- [ ] 유저 프로필 보이기
- [ ] 유저의 주문 내역 보여주기
- [ ] 찜 목록 구현(보류)
