### ISSUE TITLE
BYE-002/일반 자체 회원 가입

### ISSUE THREAD

**Issue by KimJunpyo** [codestates-seb/seb44_main_022#9]
## 요구사항 ID

BYE-002

## 요구사항

일반 자체 회원 가입

## 상세 요구사항

- ID, 비밀번호, 닉네임을 전달 받아 가입

## TODO
- [x] 각 항목당 유효성 검사
- [x] 조건이 맞지 않을 시, 에러 메시지 표시
- [ ] 모든 유효성 검사 통과 시, 로그인 페이지로 전환

## 개발 시간
4시간

**Comment by KimJunpyo** [comment]
레이아웃 완

**Comment by KimJunpyo** [comment]
유효성, 에러 메시지 완
